package de.uhh.l2g.webservices.videoprocessor.model.opencast;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Auto-generated by http://www.jsonschema2pojo.org/
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
"mimetype",
"id",
"type",
"url",
"tags"
})
public class Attachment {
	
	@JsonProperty("mimetype")
	private String mimetype;
	@JsonProperty("id")
	private String id;
	@JsonProperty("type")
	private String type;
	@JsonProperty("url")
	private String url;
	@JsonProperty("tags")
	private List<String> tags = null;
	@JsonIgnore
	private Map<String, Object> additionalProperties = new HashMap<String, Object>();
	
	@JsonProperty("mimetype")
	public String getMimetype() {
	return mimetype;
	}
	
	@JsonProperty("mimetype")
	public void setMimetype(String mimetype) {
	this.mimetype = mimetype;
	}
	
	@JsonProperty("id")
	public String getId() {
	return id;
	}
	
	@JsonProperty("id")
	public void setId(String id) {
	this.id = id;
	}
	
	@JsonProperty("type")
	public String getType() {
	return type;
	}
	
	@JsonProperty("type")
	public void setType(String type) {
	this.type = type;
	}
	
	@JsonProperty("url")
	public String getUrl() {
	return url;
	}
	
	@JsonProperty("url")
	public void setUrl(String url) {
	this.url = url;
	}
	
	@JsonProperty("tags")
	public List<String> getTags() {
	return tags;
	}
	
	@JsonProperty("tags")
	public void setTags(List<String> tags) {
	this.tags = tags;
	}
	
	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
	return this.additionalProperties;
	}
	
	@JsonAnySetter
	public void setAdditionalProperty(String name, Object value) {
	this.additionalProperties.put(name, value);
	}

}