package de.uhh.l2g.webservices.videoprocessor.model.opencast.publication;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Auto-generated by http://www.jsonschema2pojo.org/
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
"metadata",
"attachments",
"channel",
"id",
"media",
"mediatype",
"url"
})
public class Publication {
	
	@JsonProperty("metadata")
	private List<Object> metadata = null;
	@JsonProperty("attachments")
	private List<Object> attachments = null;
	@JsonProperty("channel")
	private String channel;
	@JsonProperty("id")
	private String id;
	@JsonProperty("media")
	private List<Medium> media = null;
	@JsonProperty("mediatype")
	private String mediatype;
	@JsonProperty("url")
	private String url;
	@JsonIgnore
	private Map<String, Object> additionalProperties = new HashMap<String, Object>();
	
	@JsonProperty("metadata")
	public List<Object> getMetadata() {
		return metadata;
	}
	
	@JsonProperty("metadata")
	public void setMetadata(List<Object> metadata) {
		this.metadata = metadata;
	}
	
	@JsonProperty("attachments")
	public List<Object> getAttachments() {
		return attachments;
	}
	
	@JsonProperty("attachments")
	public void setAttachments(List<Object> attachments) {
		this.attachments = attachments;
	}
	
	@JsonProperty("channel")
	public String getChannel() {
		return channel;
	}
	
	@JsonProperty("channel")
	public void setChannel(String channel) {
		this.channel = channel;
	}
	
	@JsonProperty("id")
	public String getId() {
		return id;
	}
	
	@JsonProperty("id")
	public void setId(String id) {
		this.id = id;
	}
	
	@JsonProperty("media")
	public List<Medium> getMedia() {
		return media;
	}
	
	@JsonProperty("media")
	public void setMedia(List<Medium> media) {
		this.media = media;
	}
	
	@JsonProperty("mediatype")
	public String getMediatype() {
		return mediatype;
	}
	
	@JsonProperty("mediatype")
	public void setMediatype(String mediatype) {
		this.mediatype = mediatype;
	}
	
	@JsonProperty("url")
	public String getUrl() {
		return url;
	}
	
	@JsonProperty("url")
	public void setUrl(String url) {
		this.url = url;
	}
	
	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
		return this.additionalProperties;
	}
	
	@JsonAnySetter
	public void setAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
	}

}